# Generated by Django 4.2.4 on 2023-08-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
