# Generated by Django 4.2.4 on 2023-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications_app", "0002_user_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
